// <auto-generated />
using System;
using HRMS.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRMS.Migrations
{
    [DbContext(typeof(HRMSContext))]
    [Migration("20260420125247_new_colomn_PositionId_employees")]
    partial class new_colomn_PositionId_employees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRMS.Models.Department", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("floorNumber")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("HRMS.Models.Employee", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ManagerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("positionId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("positionId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HRMS.Models.Lookup", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<int>("magerCode")
                        .HasColumnType("int");

                    b.Property<int>("minerCode")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("Lookups");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            magerCode = 0,
                            minerCode = 0,
                            name = "Employees position"
                        },
                        new
                        {
                            id = 2L,
                            magerCode = 0,
                            minerCode = 0,
                            name = "Manager"
                        },
                        new
                        {
                            id = 3L,
                            magerCode = 0,
                            minerCode = 1,
                            name = "Developer"
                        },
                        new
                        {
                            id = 4L,
                            magerCode = 0,
                            minerCode = 2,
                            name = "HR"
                        },
                        new
                        {
                            id = 5L,
                            magerCode = 1,
                            minerCode = 0,
                            name = "Department name"
                        },
                        new
                        {
                            id = 6L,
                            magerCode = 1,
                            minerCode = 1,
                            name = "Finance"
                        },
                        new
                        {
                            id = 7L,
                            magerCode = 1,
                            minerCode = 2,
                            name = "Adminstrative"
                        },
                        new
                        {
                            id = 8L,
                            magerCode = 1,
                            minerCode = 3,
                            name = "Technical"
                        });
                });

            modelBuilder.Entity("HRMS.Models.Employee", b =>
                {
                    b.HasOne("HRMS.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("HRMS.Models.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.HasOne("HRMS.Models.Lookup", "Lookup")
                        .WithMany()
                        .HasForeignKey("positionId");

                    b.Navigation("Department");

                    b.Navigation("Lookup");

                    b.Navigation("Manager");
                });
#pragma warning restore 612, 618
        }
    }
}
